//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace gchupdater.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("gchupdater.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mozilla/5.0 (Windows NT 5.1; rv:10.0.7) Gecko/20100101 Firefox/10.0.7.
        /// </summary>
        internal static string AppUserAgent {
            get {
                return ResourceManager.GetString("AppUserAgent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Critical error: {0}..
        /// </summary>
        internal static string ConCritError {
            get {
                return ResourceManager.GetString("ConCritError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current version: {0}..
        /// </summary>
        internal static string ConCurrVer {
            get {
                return ResourceManager.GetString("ConCurrVer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Done..
        /// </summary>
        internal static string ConDone {
            get {
                return ResourceManager.GetString("ConDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading file {0} from server....
        /// </summary>
        internal static string ConDownFrmServer {
            get {
                return ResourceManager.GetString("ConDownFrmServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Error!.
        /// </summary>
        internal static string ConErrText {
            get {
                return ResourceManager.GetString("ConErrText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: {0}..
        /// </summary>
        internal static string ConExError {
            get {
                return ResourceManager.GetString("ConExError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Goodbye!.
        /// </summary>
        internal static string ConGb {
            get {
                return ResourceManager.GetString("ConGb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version on server: {0}..
        /// </summary>
        internal static string ConNewVer {
            get {
                return ResourceManager.GetString("ConNewVer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installation not found. Can&apos;t update. Reinstall program from official site..
        /// </summary>
        internal static string ConNoBinFound {
            get {
                return ResourceManager.GetString("ConNoBinFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This program can&apos;t be started directly!.
        /// </summary>
        internal static string ConNoDirectStart {
            get {
                return ResourceManager.GetString("ConNoDirectStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No updates available. You have the latest version!.
        /// </summary>
        internal static string ConNoUpdatesAvail {
            get {
                return ResourceManager.GetString("ConNoUpdatesAvail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removing temporary files....
        /// </summary>
        internal static string ConRemovingTempFiles {
            get {
                return ResourceManager.GetString("ConRemovingTempFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting updater....
        /// </summary>
        internal static string ConStartWorker {
            get {
                return ResourceManager.GetString("ConStartWorker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TEAM-FORTRESS.SU OFFLINE CHECKER UPDATER.
        /// </summary>
        internal static string ConTitle {
            get {
                return ResourceManager.GetString("ConTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update available. Will download and install now..
        /// </summary>
        internal static string ConUpdateAvail {
            get {
                return ResourceManager.GetString("ConUpdateAvail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update finished..
        /// </summary>
        internal static string ConUpdateFinished {
            get {
                return ResourceManager.GetString("ConUpdateFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updating files....
        /// </summary>
        internal static string ConUpdatingFiles {
            get {
                return ResourceManager.GetString("ConUpdatingFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to gchupw.exe.
        /// </summary>
        internal static string UpdateFile {
            get {
                return ResourceManager.GetString("UpdateFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.easycoding.org/files/gchclient.txt.
        /// </summary>
        internal static string UpdateURL {
            get {
                return ResourceManager.GetString("UpdateURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to gchupdater.Resources.Wmsg.txt.
        /// </summary>
        internal static string WlcMsgResName {
            get {
                return ResourceManager.GetString("WlcMsgResName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ###########################################################################
        ///#           WELCOME TO TEAM-FORTRESS.SU OFFLINE CHECKER UPDATER           #
        ///# This console program will update offline checker to the latest version. #
        ///#                                                                         #
        ///#        (C) 2005 - 2017 EasyCoding Team. All rights reserved.            #
        ///#            Original author: V1TSK (vitaly@easycoding.org).              #
        ///#                                                  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Wmsg {
            get {
                return ResourceManager.GetString("Wmsg", resourceCulture);
            }
        }
    }
}
